plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - vendor/**/*
  TargetRubyVersion: 3.3
  DisplayCopNames: true

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Naming/AccessorMethodName:
  Exclude:
    - spec/**/*
